### ISSUE TITLE
hi:(

### ISSUE THREAD

**Issue by activator11** [ganqqwerty/addons-anki#2]
Anki 24.06.3 (d678  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10

When loading IntelliFiller ChatGPT:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\AppData\Roaming\Anki2\addons21\1416178071\__init__.py", line 11, in <module>
    from .settings_editor import SettingsWindow
  File "C:\UsersAppData\Roaming\Anki2\addons21\1416178071\settings_editor.py", line 1, in <module>
    from PyQt5.QtGui import QGuiApplication
ImportError: DLL load failed while importing QtGui: The specified module could not be found.

**Comment by ganqqwerty** [comment]
should be ok now!
